name: FrameForge
options:
  bundleIdPrefix: com.lalitkhatri
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    majorVersion: 13.3.0
targets:
  FrameForge:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - FrameForge
    info:
      path: FrameForge/Info.plist
      properties:
        GADApplicationIdentifier: ca-app-pub-8035596577604363~8815402433
    dependencies:
      - package: GoogleMobileAds
