name: FrameForge
options:
  bundleIdPrefix: com.lalitkhatri
targets:
  FrameForge:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - FrameForge
    info:
      path: FrameForge/Info.plist
